### ISSUE TITLE
Update cordova guide for usage with Evothings Workbench 2.0 and Key-based scheme

### ISSUE THREAD

**Issue by robertoandrade** [evothings/evothings-doc#91] opened 2015-11-30 18:19 UTC
I noticed the [Cordova Guide](https://github.com/evothings/evothings-doc/blob/master/build/cordova-guide.html) is still using the old IP:port with hyperlink suggestions for integration.

I got some instructions from you guys that I should be using `window.location.assign("https://deploy.evothings.com/connect/" + key);` instead (at the time I got a staging URL instead of noticed with the latest beta I'm using it's configured to publish my application on this other URL).

When I do that though I can't get my cordova app to load as it can't find the `cordova.js` when being served/reloaded through your backends. Any tips on how to go about doing this with the new key-based system?

**Comment by mikaelkindborg** [comment] 2015-12-08 13:45
@robertoandrade Thanks for pointing this out! Update of documentation is planned for next sprint.

Added issue here for the problems with loading cordova.js from a custom Cordova app: https://github.com/evothings/evothings-studio/issues/138

**Comment by mikaelkindborg** [comment] 2015-12-08 15:43
@robertoandrade I wonder if this issue is related to the problem of noyt finding cordova.js? https://github.com/evothings/evothings-studio/issues/90

**Comment by mikaelkindborg** [comment] 2015-12-08 15:44
Update documentation to mention fix for this problem: 
https://github.com/evothings/evothings-studio/issues/90

**Comment by mikaelkindborg** [comment] 2016-04-21 19:06
Investigated why connecting from custom Cordova apps does not work. Found some bugs, documented them in this issue: https://github.com/evothings/evothings-studio/issues/138

**Comment by mikaelkindborg** [comment] 2016-04-21 19:24
We should discuss whether to continue to support connecting from custom Cordova apps.

There are pros and cons to this and the situation is different with Evothings Viewer compared to Evothings Client.

Main reason for connecting from custom Cordova app:

* Making custom plugins work when using Evothings Studio

However, the problem is that one has to take several steps to make a Cordova app work:

* The Cordova app must be modified to allow connecting to the server (done in config.xml)
* The stock index.html must be modified to remove certain meta tags (see this issue: https://github.com/evothings/evothings-studio/issues/90)
* index.html must be modified to connect to the server, when app is ready for production this must be changed/switched off/removed (different code for development and production)
* The connect key has a time out set to 5 minutes, if starting the app after the key has timed out connect will fail
* To solve the connect key timeout problem the app has to be modified with a new key each time it is restarted, or a UI has to be provided that allows entering the connect key
* HTML files dragged into the Workbench must be located in the www-folder of the Cordova app, otherwise cordova.js and related files will not be found
* Thus, it is not possible to run apps that does not have the www-folder at the base path, this means the app cannot be used as a generic viewer, each custom Cordova app need to connect separately

The above steps are a recipe for errors and confusion. 

The alternative is to simply not support connecting from custom Cordova app, but to build a custom version of Evothings Viewer. What is nice with this approach:

* A custom-built Viewer can have any plugins you like
* It can run apps from any source (like the Evothings example apps)
* Apps do not have to be located in the www-folder of the Cordova app (the Viewer in this case)
* The custom Viewer can be distributed to others and still work
* It is quite easy to build the Viewer, and plan is to make it even easier to make custom Viewers
* Above steps not needed, easier to understand and describe how custom Viewers work

There is a valid case for connecting using the server URL explicitly, and that si from a web browser. When connecting from a web browser, the issue of custom plugins does not exist, so there is no need for any custom app.

Recommendation:

* We should remove the (broken) support for connecting from custom Viewers
* Further enhance the process of building custom Viewers
* Document how to connect from a web browser (valid for example for IoT apps using Web Bluetooth)





The above steps

**Comment by mikaelkindborg** [comment] 2016-05-02 12:03
Closing issue, supported method for adding custom plugins is to build Evothings Viewer.

Build of custom Viewers has been enhanced.

**Closed by mikaelkindborg** 2016-05-02 12:03 UTC
